### ISSUE TITLE
Chages.License.Fix broken repo link; Changes.Dev.IDD How to perform Issue-driven Development; Docs.Delete /docs/.git folder; Changes.Doc.AddSection Cookbooks.

### ISSUE THREAD

**Issue by CaleMcCollough** [kabuki-starship/astartup.cookbook#13]
# Details

## Problem

The repo link in the License is broken. Issue-driven development is a very technical subject worthy of its own chapter but it's part of Development. We also need a DRY instruction on how to make a Cookbook.

## Solution

Development is not a Part that contains a Chapter on IDD. Fix the broken link.

**Comment by AStarCale** [comment]
Bumped original ticket to #101.
