### ISSUE TITLE
Changes.GettingStarted.Add instructions on how to use the Kabuki Starship markdown templates.

### ISSUE THREAD

**Issue by CaleMcCollough** [kabuki-starship/astartup.cookbook#18]
# DRY

## Problem

We need these super cook markdown templates that need DRY instructions.

## Solution

Add a section that covers how to use the Markdown Software Engineering, Markdown Game Design, and Markdown Cookbook templates. We need to make the chapter generalizable to other industries so we need to re-add the Markdown Hardware Engineering templates ASAP.

## Hierarchy

* Flat

**Comment by AStarCale** [comment]
Bumped original ticket to #103.

**Comment by AStarCale** [comment]
Bumped original ticket to #104.
